// Stamps src/version.ts with the current commit SHA + UTC build time so the
// production /api/version endpoint always identifies the running build.
// Node builtins only. Runs as part of `npm run deploy`; safe to run anytime.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src', 'version.ts');

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { encoding: 'utf8', cwd: root }).trim() || 'unknown';
} catch {
  // Not a git checkout (e.g. remote build cache) — keep the last stamped value.
  try {
    if (existsSync(out)) {
      const m = /VERSION_COMMIT = "([^"]*)"/.exec(readFileSync(out, 'utf8'));
      if (m?.[1]) commit = m[1];
    }
  } catch {
    // fall through with 'unknown'
  }
}
const builtAt = new Date().toISOString();
writeFileSync(
  out,
  `// AUTO-GENERATED by scripts/stamp-version.js - do not edit by hand.\n` +
    `export const VERSION_COMMIT = ${JSON.stringify(commit)};\n` +
    `export const VERSION_BUILT_AT = ${JSON.stringify(builtAt)};\n`,
);
console.log(`stamped version: ${commit} @ ${builtAt}`);
